### PR TITLE
Fixed and improved MDR1986VE3.h + cleanup

### PR DESCRIPTION
**Pull request by in4lio**
1. **MDR1986VE3.h**: some definitions have been imported from **MDR1986VE1T.h**
2. **MDR1986VE3.h**: fixed `__MPU_PRESENT`, `__NVIC_PRIO_BITS`, `EBC_RAM_CYCLES_WS_HOLD_Msk`
3. **MDR1986VE3.h**: replaced _TABs_
4. cleanup

### CODE REVIEW

**Comment by eldarkg** [comment]
[Where is in doc?](https://github.com/in4lio/emdr1986x-std-per-lib/blob/d5e55dab36a6b5330a116455d4794305660c7d91/CMSIS/CM1/DeviceSupport/MDR1986VE3/inc/MDR1986VE3.h#L2523)
```C
#define TIMER_CNTRL_CNT_MODE_UP_DOWN_DIR_AUTO_EVENT_1   0x03

**Comment by eldarkg** [comment]
Where are this bits?
```
Таблица 269 – Описание бит регистра CNTRL
EVENT_SEL[3:0]:
4’b1001 – событие заднего фронта ETR
4’b1010 – CNT == ARR в таймере 4

**Comment by eldarkg** [comment]
[Code](https://github.com/in4lio/emdr1986x-std-per-lib/blob/2176b05a6701ea96c5de887ceeba8852ab745f02/CMSIS/CM1/DeviceSupport/MDR1986VE3/inc/MDR1986VE3.h#L928):
```C
#define RST_CLK_CLOCK_STATUS_HSE_ALL_RDY        ((uint32_t)0x0000000C)
```
it will be good to write:
```C
#define RST_CLK_CLOCK_STATUS_HSE_ALL_RDY        (RST_CLK_CLOCK_STATUS_HSE_RDY |\
                                                 RST_CLK_CLOCK_STATUS_HSE_RDY2)

**Comment by eldarkg** [comment]
Define constants that defined yet:
[1](https://github.com/in4lio/emdr1986x-std-per-lib/blob/2176b05a6701ea96c5de887ceeba8852ab745f02/CMSIS/CM1/DeviceSupport/MDR1986VE3/inc/MDR1986VE3.h#L2613)
[2](https://github.com/in4lio/emdr1986x-std-per-lib/blob/2176b05a6701ea96c5de887ceeba8852ab745f02/CMSIS/CM1/DeviceSupport/MDR1986VE3/inc/MDR1986VE3.h#L2616)
[3](https://github.com/in4lio/emdr1986x-std-per-lib/blob/2176b05a6701ea96c5de887ceeba8852ab745f02/CMSIS/CM1/DeviceSupport/MDR1986VE3/inc/MDR1986VE3.h#L2617)
This lines should be deleted.

**Comment by eldarkg** [comment]
In accordance:
```
Таблица 293 – Описание бит регистра ADC1_CFG
DelayGo[2:0]
000 – 0 тактов PCLK
001 – 1 такт PCLK
...
111 – 7 тактов PCLK
```
but you have [defined](https://github.com/in4lio/emdr1986x-std-per-lib/blob/2176b05a6701ea96c5de887ceeba8852ab745f02/CMSIS/CM1/DeviceSupport/MDR1986VE3/inc/MDR1986VE3.h#L2935) range 1-8 clocks:
```C
#define ADC1_CFG_DELAY_GO_1_CPU_CLK             0x00
#define ADC1_CFG_DELAY_GO_2_CPU_CLK             0x01
#define ADC1_CFG_DELAY_GO_3_CPU_CLK             0x02
#define ADC1_CFG_DELAY_GO_4_CPU_CLK             0x03
#define ADC1_CFG_DELAY_GO_5_CPU_CLK             0x04
#define ADC1_CFG_DELAY_GO_6_CPU_CLK             0x05
#define ADC1_CFG_DELAY_GO_7_CPU_CLK             0x06
#define ADC1_CFG_DELAY_GO_8_CPU_CLK             0x07
```

**Comment by eldarkg** [comment]
[Where you found this bits](https://github.com/in4lio/emdr1986x-std-per-lib/blob/2176b05a6701ea96c5de887ceeba8852ab745f02/CMSIS/CM1/DeviceSupport/MDR1986VE3/inc/MDR1986VE3.h#L2945):
```C
/* Delay ADC Modes */
#define ADC1_CFG_DELAY_ADC_1_CPU_CLK            0x00
#define ADC1_CFG_DELAY_ADC_2_CPU_CLK            0x01
#define ADC1_CFG_DELAY_ADC_3_CPU_CLK            0x02
#define ADC1_CFG_DELAY_ADC_4_CPU_CLK            0x03
#define ADC1_CFG_DELAY_ADC_5_CPU_CLK            0x04
#define ADC1_CFG_DELAY_ADC_6_CPU_CLK            0x05
#define ADC1_CFG_DELAY_ADC_7_CPU_CLK            0x06
#define ADC1_CFG_DELAY_ADC_8_CPU_CLK            0x07
#define ADC1_CFG_DELAY_ADC_9_CPU_CLK            0x08
#define ADC1_CFG_DELAY_ADC_10_CPU_CLK           0x09
#define ADC1_CFG_DELAY_ADC_11_CPU_CLK           0x0A
#define ADC1_CFG_DELAY_ADC_12_CPU_CLK           0x0B
#define ADC1_CFG_DELAY_ADC_13_CPU_CLK           0x0C
#define ADC1_CFG_DELAY_ADC_14_CPU_CLK           0x0D
#define ADC1_CFG_DELAY_ADC_15_CPU_CLK           0x0E
#define ADC1_CFG_DELAY_ADC_16_CPU_CLK           0x0F
```
I see DelayADC[3:0] are reserved.

**Comment by eldarkg** [comment]
**Info**: this PR fix next definition:
```C
#define EBC_RAM_CYCLES_WS_HOLD_Msk              ((uint32_t)0x00003800)
```

**Comment by eldarkg** [comment]
Where is defines eth buffer sizes in doc:
```C
#define MDR_ETHERNET1_BUF_SIZE    8192
#define MDR_ETHERNET1_BUF_SIZE    8192
```

**Comment by eldarkg** [comment]
This was the my last question

**Comment by in4lio** [comment]
All changes comes from ["MDR1986VE1T.h"](https://github.com/eldarkg/emdr1986x-std-per-lib/blob/master/CMSIS/CM1/DeviceSupport/MDR1986VE1T/inc/MDR1986VE1T.h). I should check and fix both headers.

**Comment by in4lio** [comment]
```
#define TIMER_CNTRL_CNT_MODE_UP_DOWN_DIR_AUTO_EVENT_1   0x03
```
It seeped from 1986ВЕ9x. Removed...

**Comment by in4lio** [comment]
```
// CCR1 EN = 1
...
#define TIMER_CH_CNTRL_OCCM_SW_REF_CNT_CCR              0x03
```
Renamed to `TIMER_CH_CNTRL_OCCM_SW_REF_CNT_CCR_OR_CNT_CCR1`
for "MDR32Fx.h", "MDR1986VE1T.h" and "MDR1986VE3.h"

**Comment by in4lio** [comment]
```
/* Delay ADC Modes */
#define ADC1_CFG_DELAY_ADC_1_CPU_CLK            0x00
...
```
Oops... not implemented in 1986ВЕ3 at all

**Comment by in4lio** [comment]
> Where is defines eth buffer sizes in doc?

"Буфер 8 кБ" on the scheme:
image

**Comment by in4lio** [comment]
Done

**Comment by eldarkg** [comment]
@in4lio Sorry. Maybe we should to keep 
```C
#define ADC1_CFG_DELAY_GO_1_CPU_CLK             0x00
```
delete
```C
#define ADC1_CFG_DELAY_GO_0_CPU_CLK             0x00
```
see table
```
Таблица 290 – Время заряда внутренней емкости АЦП и время преобразования
```

**Comment by eldarkg** [comment]
Repeat:
Where are this bits?
```
Таблица 269 – Описание бит регистра CNTRL
EVENT_SEL[3:0]:
4’b1001 – событие заднего фронта ETR
4’b1010 – CNT == ARR в таймере 4
```

**Comment by eldarkg** [comment]
Please revert
```C
#define ADC1_CFG_DELAY_ADC_1_CPU_CLK        0x00
#define ADC1_CFG_DELAY_GO_1_CPU_CLK         0x00
```

**Comment by in4lio** [comment]
Take a look, please.

**Comment by eldarkg** [comment]
Good work. Thank you

**Pull request merged**
